---
name: PMVNGVipJoin
version: 1.0.0
main: DavidGlitch04\PMVNGVipJoin\Main
api: 4.0.0
website: https://github.com/PMVNG
author: PMVNG
authors: [DavidGlitch04]
depend: [PurePerms]
src-namespace-prefix: DavidGlitch04\PMVNGVipJoin
...
